# Generated by Django 2.1.1 on 2019-02-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companion',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hobby',
            old_name='name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personalityfeature',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='human_or_pet',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='personalityfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personalityfeature',
            name='is_active',
        ),
        migrations.AddField(
            model_name='companion',
            name='baby',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='bird',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='cat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='daughter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='dog',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='father',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='fish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='friend_m',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='friend_w',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='husband',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='lizard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='mother',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='snail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='snake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='son',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='teenager_m',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='teenager_w',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='wife',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='camping',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='cinema',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='collecting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='cooking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='dancing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='doing_music',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='drawing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='fishing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='handiwork',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='herbalism',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='hunting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='learning_history',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='learning_languages',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='magician',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='museums',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='music',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='photo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='reading',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='shoping',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='sport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='theater',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='traveling',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='ambicioznyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='ambivert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='analitycheskyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='bezzabotnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='domosed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='emocionalnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='extravert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='gumanitarnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='introvert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='ishyshyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='lenivyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='molchalivyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='neposeda',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='neprityazatelnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='optimalist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='optimist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='perfeczianist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='pessimist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='racionalnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='razgovorchivyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='serieznyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='snishoditelnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='spokoynyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='trebovatelnyi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityfeature',
            name='trudolybivyi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
